repos:
  -   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
      rev: v0.8.0
      hooks:
      -   id: pre-commit-update
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff                 # format + lint + import-sort
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks: [id: codespell]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks: [id: detect-secrets]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks: [id: shellcheck]