global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'meraki-dashboard-exporter'
    static_configs:
      - targets: ['exporter:9090']
    scrape_interval: 300s  # Match the exporter's collection interval
    scrape_timeout: 60s